USE PhrasePlanter

CREATE TABLE Users (
    UserID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    UserAccount CHAR(20) NOT NULL UNIQUE,
    UserScecretHash CHAR(20) NOT NULL,
    Name CHAR(20) NOT NULL DEFAULT('NO NAME')
)
GO
